language: ruby

services:
  - postgresql

before_script:
  # - psql -U postgres -c 'CREATE DATABASE chitter_db_test;'
  # - psql -U postgres -d chitter_db_test -f db/01_create_makers_table.sql
  # - psql -U postgres -d chitter_db_test -f db/02_create_peeps_table.sql

script:
  - bundle exec rspec
  - bundle exec rake setup
